name: sc_client
description: Set of tools helping a spaceman thrive in Star Citizen
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.6+7

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.7
  cupertino_icons: ^1.0.6
  go_router: ^13.0.1
  intl: ^0.19.0
  currency_text_input_formatter: ^2.1.13
  package_info_plus: ^4.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
