# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Firebase Deploy (via `b/prod`)

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

  workflow_dispatch:

jobs:
  build_deploy_web:
    name: Build & Deploy Web to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.0-17.0.pre'
          channel: 'master'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter analyze
      - run: flutter test --coverage
      - run: flutter build web --release --web-renderer=html
        
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web

      - name: Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
         repoToken: '${{ secrets.GITHUB_TOKEN }}'
         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SC_ASSISTANT }}'
         projectId: sc-assistant
         channelId: live
        env:
         FIREBASE_CLI_PREVIEWS: hostingchannels